services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=2.24.31.74
      - MYSQL_PORT=3320
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1xgu0hfsephxfav9
      - MYSQL_DATABASE=blasto
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
    restart: unless-stopped